<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.2.0</Version>
    <Product>bvds-for-windows</Product>
    <AssemblyTitle>B站视频下载器</AssemblyTitle>
    <Copyright>MIT License</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BvdsForWindows.Core\BvdsForWindows.Core.csproj" />
  </ItemGroup>

</Project>
